/*
 * Copyright (c) 2026 by Naohide Sano, All rights reserved.
 *
 * Programmed by Naohide Sano
 */

package vavi.sound.wind;


/**
 * PcmWaveform. the third slot of an oscillator.
 * <p>
 * {@link #None} leaves the slot as the pulse width modulated wave the first IFW versions
 * had, anything else replaces it with a single cycle instrument wave. the original waves
 * live in the plug-in binary and are not distributable, so each one is rebuilt here from
 * the harmonic amplitudes of the instrument it is named after ({@link #harmonics()}).
 * versions that predate this parameter write it as a plain {@code 0}, which is what
 * {@link #None} is still written as so that such a version can read the file back.
 *
 * @author <a href="mailto:umjammer@gmail.com">Naohide Sano</a> (nsano)
 * @version 0.00 2026-09-04 nsano initial version <br>
 */
public enum PcmWaveform implements Labeled {

    /** pulse width modulated wave */
    None("0", new float[0]),
    /** alto sax, strong even and odd harmonics with a formant around the 4th */
    ASax("ASax", new float[] {1, .8f, .65f, .7f, .45f, .3f, .22f, .18f, .12f, .09f, .07f, .05f}),
    /** clarinet, odd harmonics only */
    Clarinet("Clarinet", new float[] {1, .04f, .7f, .03f, .4f, .02f, .2f, .01f, .08f, 0, .04f}),
    /** the sawtooth of a well known 1987 linear synthesizer, slightly softened */
    D50Saw("D50Saw", new float[] {1, .5f, .34f, .25f, .2f, .17f, .14f, .12f, .11f, .1f, .09f, .08f, .07f, .06f, .05f, .04f}),
    /** harmonica, reedy with a dip in the low harmonics */
    Harmonica("Harmonica", new float[] {1, .55f, .8f, .5f, .55f, .35f, .28f, .2f, .15f, .1f, .08f}),
    /** oboe, weak fundamental and a strong second and third */
    Oboe("Oboe", new float[] {.5f, .9f, 1, .6f, .5f, .38f, .3f, .22f, .15f, .1f, .07f}),
    /** trombone */
    Tb("Tb", new float[] {1, .9f, .7f, .5f, .35f, .25f, .18f, .12f, .09f, .06f, .04f}),
    /** trumpet, bright with a formant around the 5th */
    Tp("Tp", new float[] {.7f, .9f, 1, .85f, .9f, .6f, .45f, .3f, .2f, .14f, .1f, .07f});

    /** one cycle of every wave, filled in on demand */
    private static final int TABLE_SIZE = 2048;

    private final String label;
    private final float[] harmonics;
    private float[] table;

    PcmWaveform(String label, float[] harmonics) {
        this.label = label;
        this.harmonics = harmonics;
    }

    @Override
    public String label() {
        return label;
    }

    @Override
    public String[] aliases() {
        return this == None ? new String[] {"---", "None", "Off", "PWM"} : new String[0];
    }

    /** relative amplitude of the 1st, 2nd, 3rd ... harmonic */
    public float[] harmonics() {
        return harmonics.clone();
    }

    /**
     * Reads one cycle.
     *
     * @param phase 0 .. 1
     * @return -1 .. 1, 0 for {@link #None} which is generated by the oscillator itself
     */
    public float value(float phase) {
        if (this == None) {
            return 0;
        }
        float[] t = table();
        int i = (int) (phase * TABLE_SIZE) & TABLE_SIZE - 1;
        int j = i + 1 & TABLE_SIZE - 1;
        float f = phase * TABLE_SIZE - (float) Math.floor(phase * TABLE_SIZE);
        return t[i] + (t[j] - t[i]) * f;
    }

    /** */
    private float[] table() {
        float[] t = table;
        if (t == null) {
            t = new float[TABLE_SIZE];
            float peak = 0;
            for (int i = 0; i < TABLE_SIZE; i++) {
                double v = 0;
                for (int h = 0; h < harmonics.length; h++) {
                    v += harmonics[h] * Math.sin(2 * Math.PI * (h + 1) * i / TABLE_SIZE);
                }
                t[i] = (float) v;
                peak = Math.max(peak, Math.abs(t[i]));
            }
            for (int i = 0; i < TABLE_SIZE; i++) {
                t[i] /= peak;
            }
            table = t;
        }
        return t;
    }

    /** */
    public static PcmWaveform valueOfLabel(String label) {
        return Labeled.valueOfLabel(PcmWaveform.class, label);
    }
}
